services:
  analyze_service:
    container_name: analyze_service
    build:
      dockerfile: ./docker/Dockerfile.hmr
      context: ../
      target: "development"
    volumes:
      - ../:/app
    ports:
      - "8080:8080"
    environment:
      # DOCKER_DB_NAME: postdb.tsod.home.arpa
      # CI_COMMIT_BRANCH: testing
      TZ: Europe/Moscow
      # USERS_CONFIG_SERVICE_PATH: ./cfg/cfg.json
      # USERS_CONFIG_DB_PATH: ./cfg/cfg-db.json
      # USERS_CONFIG_KAFKA_PATH: ./cfg/cfg-kafka.json
      # USERS_CONFIG_DB_SEED: ./cfg/seed.json
      # USERS_TLS_CERT_PATH: ./mkcert/_wildcard.tsod.ru+3.pem
      # USERS_TLS_KEY_PATH: ./mkcert/_wildcard.tsod.ru+3-key.pem
